#Database configuration
jdbc.driverClassName: com.mysql.jdbc.Driver
jdbc.url: jdbc:mysql://localhost:3306/shadowfish # Needs to be filled with correct info
jdbc.username: daheka # Needs to be filled with correct info
jdbc.password: Hammie12336612 # Needs to be filled with correct info

#Hibernate configuration
hibernate.dialect: org.hibernate.dialect.HSQLDialect
hibernate.show_sql: true
hibernate.hbm2ddl.auto: update
hibernate.generate_statistics: true

error.whitelabel.enabled: false