#Database configuration
spring.datasource.url: jdbc:mysql://localhost:3306/shadowfish
spring.datasource.username: daheka
spring.datasource.password: Hammie12336612
spring.datasource.driverClassName: com.mysql.jdbc.Driver

#Hibernate configuration
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.generate-ddl: true
#hibernate.dialect: org.hibernate.dialect.HSQLDialect
#hibernate.show_sql: true
#hibernate.hbm2ddl.auto: create
#hibernate.generate_statistics: true

error.whitelabel.enabled: false